### ISSUE TITLE
Fails with relative URLs

### ISSUE THREAD

**Issue by digitarald** [lencioni/remote-source-map-explorer#1]
STR:
`> remote-source-map-explorer https://perf-html.io/9eea8cd330febdcdf53d.bundle.js`

The file uses:

`//# sourceMappingURL=9eea8cd330febdcdf53d.bundle.js.map`

Error:

```
Error: sourceMappingURL does not look like a URL: 9eea8cd330febdcdf53d.bundle.js.map
    at get.then (/Users/hkirschner/.config/yarn/global/node_modules/remote-source-map-explorer/index.js:76:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by lencioni** [comment]
Thanks for the bug report. This is an example of me being lazy.

https://github.com/lencioni/remote-source-map-explorer/blob/f60e86798d796805aeebfc27c83f6f1bcdcd5470/index.js#L74-L77

I'd love to review a PR that fixes it. Otherwise, hopefully I'll be able to fix it soon.

**Comment by lencioni** [comment]
@digitarald Thanks again for the report! This should be fixed in 1.0.2.

**Comment by lencioni** [comment]
By the way, here is your (static) visualization:

<img width="1432" alt="screen shot 2018-08-16 at 4 21 28 am" src="https://user-images.githubusercontent.com/195534/44205654-e85e3380-a10b-11e8-924e-5c16cf136ead.png">

**Comment by digitarald** [comment]
@lencioni that was quick, now I need to find another problem so I can contribute. Thanks for the static viz (kudos to the perf team for keeping a clean code base)!
